### ISSUE TITLE
[question] 0.11.0 on 4.0.0-M3 java.lang.NoSuchMethodError: alwaysApplyingWhenNonNull()

### ISSUE THREAD

**Issue by rchan1611** [spring-projects/spring-grpc#273]
I've noticed some churn while this project prepares for Spring Boot 4 and a pending MR in that repo.In any case is it expected that 0.11.0 does not work with 4.0.0-M3?

```
Caused by: java.lang.NoSuchMethodError: 'org.springframework.boot.context.properties.PropertyMapper org.springframework.boot.context.properties.PropertyMapper.alwaysApplyingWhenNonNull()'
        at org.springframework.grpc.autoconfigure.server.DefaultServerFactoryPropertyMapper.customizeServerBuilder(DefaultServerFactoryPropertyMapper.java:50)
        at org.springframework.grpc.autoconfigure.server.NettyServerFactoryPropertyMapper.customizeServerBuilder(NettyServerFactoryPropertyMapper.java:37)
        at org.springframework.grpc.server.DefaultGrpcServerFactory.lambda$configure$0(DefaultGrpcServerFactory.java:171)
        at java.base/java.util.ImmutableCollections$List12.forEach(ImmutableCollections.java:681)
        at org.springframework.grpc.server.DefaultGrpcServerFactory.configure(DefaultGrpcServerFactory.java:171)
        at org.springframework.grpc.server.DefaultGrpcServerFactory.createServer(DefaultGrpcServerFactory.java:112)
        at org.springframework.grpc.server.lifecycle.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:124)
        at org.springframework.grpc.server.lifecycle.GrpcServerLifecycle.start(GrpcServerLifecycle.java:73)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:420)
        ... 40 more
```

**Comment by onobc** [comment]
👋🏻 @rchan1611 ,

> I've noticed some churn while this project prepares for Spring Boot 4 and a pending https://github.com/spring-projects/spring-boot/pull/47288 in that repo.

True. Sorry for any inconvenience as we prepare for the consumption of the project in Spring Boot.

> In any case is it expected that 0.11.0 does not work with 4.0.0-M3?

Correct, `0.11.0` is not expected to work w/ `4.0.x`.  Although, it is not a ton of changes to make it work w/ `4.0.x` (e.g the `PropertyMapper` API change noticed in the issue description above).

> Is there a way to test a 1.0.0-SNAPSHOT(?) with M3 ?

So `1.0.x` expects the autoconfiguration to reside in Spring Boot. Currently the only place that is true is in the pending Spring Boot PR you mentioned above. As such, you can checkout that PR branch and build and run locally and things should work as expected. However, the PR is in progress and is changing as I still have review feedback to incorporate. 

> [!NOTE]
> If it does not work though,  do not be surprised as things are in flux (PR). Reporting any breakages in the above configuration will not be helpful. 

Thanks,
Chris
